package setup

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/rrrrrredy/beforedone/internal/model"
	"github.com/rrrrrredy/beforedone/internal/repository"
)

const piGeneratedMarker = "// Code generated by `beforedone setup pi`; DO NOT EDIT."

type PiResult struct {
	SchemaVersion int      `json:"schema_version"`
	ExtensionPath string   `json:"extension_path"`
	Changed       bool     `json:"changed"`
	Removed       bool     `json:"removed,omitempty"`
	Warnings      []string `json:"warnings,omitempty"`
}

func Pi(repo *repository.Repository) (*PiResult, error) {
	executable, err := resolvedExecutable()
	if err != nil {
		return nil, err
	}
	content, err := renderPiExtension(executable)
	if err != nil {
		return nil, err
	}

	path := filepath.Join(repo.Root, ".pi", "extensions", "beforedone.ts")
	result := &PiResult{SchemaVersion: model.SchemaVersion, ExtensionPath: path}
	if existing, err := os.ReadFile(path); err == nil {
		if !IsGeneratedPiExtension(existing) {
			return nil, fmt.Errorf("refusing to overwrite non-BeforeDone Pi extension %s", path)
		}
		if bytes.Equal(existing, content) {
			result.Warnings = piWarnings()
			return result, nil
		}
	} else if !os.IsNotExist(err) {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return nil, err
	}
	result.Changed = true
	result.Warnings = piWarnings()
	return result, nil
}

func RemovePi(repo *repository.Repository) (*PiResult, error) {
	path := filepath.Join(repo.Root, ".pi", "extensions", "beforedone.ts")
	result := &PiResult{SchemaVersion: model.SchemaVersion, ExtensionPath: path}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return result, nil
	}
	if err != nil {
		return nil, err
	}
	if !IsGeneratedPiExtension(data) {
		return nil, fmt.Errorf("refusing to remove non-BeforeDone Pi extension %s", path)
	}
	if err := os.Remove(path); err != nil {
		return nil, err
	}
	result.Changed = true
	result.Removed = true
	return result, nil
}

func IsGeneratedPiExtension(data []byte) bool {
	return bytes.HasPrefix(data, []byte(piGeneratedMarker+"\n"))
}

func resolvedExecutable() (string, error) {
	executable, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("resolve BeforeDone executable: %w", err)
	}
	if resolved, resolveErr := filepath.EvalSymlinks(executable); resolveErr == nil {
		executable = resolved
	}
	executable, err = filepath.Abs(executable)
	if err != nil {
		return "", fmt.Errorf("resolve absolute BeforeDone executable: %w", err)
	}
	return executable, nil
}

func renderPiExtension(executable string) ([]byte, error) {
	encodedExecutable, err := json.Marshal(executable)
	if err != nil {
		return nil, err
	}
	content := fmt.Sprintf(piExtensionTemplate, encodedExecutable)
	return []byte(strings.ReplaceAll(content, "\r\n", "\n")), nil
}

func piWarnings() []string {
	return []string{
		"review and trust the generated .pi project extension before starting Pi",
		"Pi evaluates BeforeDone after agent_settled and can trigger one corrective continuation; it cannot suppress the first unsupported final message",
		"rerun `beforedone setup pi` if the BeforeDone executable path changes",
	}
}

const piExtensionTemplate = piGeneratedMarker + `
// This project-local extension records bounded lifecycle metadata and asks the
// BeforeDone CLI for the completion decision. It never persists prompt text,
// tool arguments, or tool output.

import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";
import { randomUUID } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const BEFORE_DONE_EXECUTABLE = %s;
const STATE_ENTRY = "beforedone.pi.stop-state.v1";
const COMMAND_TIMEOUT_MS = 60_000;

type EventType =
  | "SessionStarted"
  | "PromptSubmitted"
  | "ToolStarted"
  | "ToolFinished"
  | "AgentStopping"
  | "SessionEnded";

type NormalizedEvent = {
  schema_version: 1;
  id: string;
  occurred_at: string;
  type: EventType;
  source: "pi";
  session_id?: string;
  turn_id?: string;
  cwd?: string;
  tool_name?: string;
  exit_code?: number;
  summary?: string;
  attributes?: Record<string, string>;
};

type GateResult = {
  schema_version: 1;
  decision: "allow" | "block";
  verdict: "PASS" | "FAIL" | "INCONCLUSIVE";
  reason?: string;
  system_message?: string;
};

type StopState = {
  schema_version: 1;
  prompt_id: string;
  corrective_continuation_used: boolean;
};

function newStopState(): StopState {
  return {
    schema_version: 1,
    prompt_id: randomUUID(),
    corrective_continuation_used: false,
  };
}

function isStopState(value: unknown): value is StopState {
  if (typeof value !== "object" || value === null) return false;
  const state = value as Partial<StopState>;
  return (
    state.schema_version === 1 &&
    typeof state.prompt_id === "string" &&
    typeof state.corrective_continuation_used === "boolean"
  );
}

function errorText(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function commandFailure(stdout: string, stderr: string, code: number): string {
  const detail = (stderr.trim() || stdout.trim() || "no diagnostic output").slice(0, 2000);
  return "BeforeDone command exited " + code + ": " + detail;
}

export default function beforeDonePi(pi: ExtensionAPI) {
  let stopState = newStopState();
  let currentTurnID = "";
  let ownCorrectionPending = false;
  let persistenceWarningShown = false;
  let ingestQueue: Promise<void> = Promise.resolve();

  function sessionID(ctx: ExtensionContext): string {
    return ctx.sessionManager.getSessionId();
  }

  function event(
    ctx: ExtensionContext,
    type: EventType,
    fields: Partial<Omit<NormalizedEvent, "schema_version" | "id" | "occurred_at" | "type" | "source">> = {},
  ): NormalizedEvent {
    return {
      schema_version: 1,
      id: "pi-" + randomUUID(),
      occurred_at: new Date().toISOString(),
      type,
      source: "pi",
      session_id: sessionID(ctx),
      turn_id: currentTurnID || undefined,
      cwd: ctx.cwd,
      ...fields,
    };
  }

  async function withTemporaryEvent<T>(value: NormalizedEvent, action: (path: string) => Promise<T>): Promise<T> {
    const directory = await mkdtemp(join(tmpdir(), "beforedone-pi-"));
    const path = join(directory, "event.json");
    try {
      await writeFile(path, JSON.stringify(value), { encoding: "utf8", mode: 0o600 });
      return await action(path);
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  }

  async function ingestNow(value: NormalizedEvent, cwd: string): Promise<void> {
    await withTemporaryEvent(value, async (path) => {
      const result = await pi.exec(
        BEFORE_DONE_EXECUTABLE,
        ["adapter", "ingest", path, "--json"],
        { cwd, timeout: COMMAND_TIMEOUT_MS },
      );
      if (result.killed || result.code !== 0) {
        throw new Error(commandFailure(result.stdout, result.stderr, result.code));
      }
    });
  }

  function persist(value: NormalizedEvent, cwd: string): Promise<void> {
    const pending = ingestQueue.then(() => ingestNow(value, cwd));
    ingestQueue = pending.catch(() => undefined);
    return pending;
  }

  async function persistObserved(value: NormalizedEvent, ctx: ExtensionContext): Promise<void> {
    try {
      await persist(value, ctx.cwd);
      persistenceWarningShown = false;
    } catch (error) {
      if (!persistenceWarningShown) {
        ctx.ui.notify("BeforeDone could not record Pi lifecycle metadata: " + errorText(error), "warning");
        persistenceWarningShown = true;
      }
    }
  }

  async function evaluateGate(ctx: ExtensionContext): Promise<GateResult> {
    const result = await pi.exec(BEFORE_DONE_EXECUTABLE, ["gate", "--json"], {
      cwd: ctx.cwd,
      timeout: COMMAND_TIMEOUT_MS,
    });
    if (result.killed || ![0, 1, 2].includes(result.code)) {
      throw new Error(commandFailure(result.stdout, result.stderr, result.code));
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(result.stdout);
    } catch (error) {
      throw new Error("BeforeDone gate returned invalid JSON: " + errorText(error));
    }
    if (typeof parsed !== "object" || parsed === null) {
      throw new Error("BeforeDone gate returned a non-object result");
    }
    const gate = parsed as Partial<GateResult>;
    if (
      gate.schema_version !== 1 ||
      (gate.decision !== "allow" && gate.decision !== "block") ||
      !["PASS", "FAIL", "INCONCLUSIVE"].includes(gate.verdict || "")
    ) {
      throw new Error("BeforeDone gate returned an incompatible result");
    }
    return gate as GateResult;
  }

  function persistStopState(ctx: ExtensionContext, failure: string): boolean {
    try {
      pi.appendEntry(STATE_ENTRY, stopState);
      return true;
    } catch (error) {
      ctx.ui.notify(failure + ": " + errorText(error), "error");
      return false;
    }
  }

  function restoreStopState(ctx: ExtensionContext): void {
    stopState = newStopState();
    for (const entry of ctx.sessionManager.getBranch()) {
      if (entry.type === "custom" && entry.customType === STATE_ENTRY && isStopState(entry.data)) {
        stopState = entry.data;
      }
    }
  }

  function correctivePrompt(reason: string): string {
    return (
      reason +
      "\n\nBeforeDone blocked completion. Continue the task, produce the missing evidence with the requested " +
      "beforedone check commands, and only report completion after beforedone gate returns PASS."
    );
  }

  function requestOneCorrection(result: GateResult, ctx: ExtensionContext): void {
    if (result.decision !== "block") {
      if (result.verdict === "INCONCLUSIVE") {
        ctx.ui.notify(result.system_message || "BeforeDone evidence is INCONCLUSIVE.", "warning");
      }
      return;
    }
    if (stopState.corrective_continuation_used) {
      ctx.ui.notify(
        "BeforeDone still blocks completion; the one automatic corrective continuation for this prompt was already used.",
        "warning",
      );
      return;
    }

    stopState = { ...stopState, corrective_continuation_used: true };
    if (!persistStopState(ctx, "BeforeDone could not persist the corrective-continuation guard")) {
      return;
    }
    ownCorrectionPending = true;
    try {
      pi.sendUserMessage(correctivePrompt(result.reason || "BeforeDone requires fresh evidence before completion."));
    } catch (error) {
      ownCorrectionPending = false;
      stopState = { ...stopState, corrective_continuation_used: false };
      persistStopState(ctx, "BeforeDone could not restore the corrective-continuation guard");
      ctx.ui.notify("BeforeDone could not start the corrective continuation: " + errorText(error), "error");
    }
  }

  pi.on("session_start", async (sourceEvent, ctx) => {
    restoreStopState(ctx);
    currentTurnID = "";
    await persistObserved(
      event(ctx, "SessionStarted", { attributes: { reason: sourceEvent.reason } }),
      ctx,
    );
  });

  pi.on("input", async (sourceEvent, ctx) => {
    if (
      sourceEvent.source === "extension" &&
      (ownCorrectionPending || stopState.corrective_continuation_used)
    ) {
      ownCorrectionPending = false;
    } else {
      ownCorrectionPending = false;
      stopState = newStopState();
      persistStopState(ctx, "BeforeDone could not persist the new-prompt retry guard");
    }
    currentTurnID = "";
    const attributes: Record<string, string> = {
      input_source: sourceEvent.source,
      has_images: String((sourceEvent.images?.length || 0) > 0),
    };
    if (sourceEvent.streamingBehavior) attributes.streaming_behavior = sourceEvent.streamingBehavior;
    await persistObserved(
      event(ctx, "PromptSubmitted", { summary: "Pi input received", attributes }),
      ctx,
    );
  });

  pi.on("turn_start", (sourceEvent, ctx) => {
    currentTurnID = sessionID(ctx) + ":turn:" + sourceEvent.turnIndex;
  });

  pi.on("tool_execution_start", async (sourceEvent, ctx) => {
    await persistObserved(
      event(ctx, "ToolStarted", {
        tool_name: sourceEvent.toolName,
        summary: "Pi tool execution started",
        attributes: { tool_call_id: sourceEvent.toolCallId },
      }),
      ctx,
    );
  });

  pi.on("tool_execution_end", async (sourceEvent, ctx) => {
    await persistObserved(
      event(ctx, "ToolFinished", {
        tool_name: sourceEvent.toolName,
        exit_code: sourceEvent.isError ? 1 : 0,
        summary: sourceEvent.isError ? "Pi tool execution failed" : "Pi tool execution finished",
        attributes: {
          tool_call_id: sourceEvent.toolCallId,
          is_error: String(sourceEvent.isError),
        },
      }),
      ctx,
    );
  });

  pi.on("agent_settled", async (_sourceEvent, ctx) => {
    const stopping = event(ctx, "AgentStopping", { summary: "Pi agent settled" });
    try {
      await persist(stopping, ctx.cwd);
    } catch (error) {
      requestOneCorrection(
        {
          schema_version: 1,
          decision: "block",
          verdict: "INCONCLUSIVE",
          reason:
            "BeforeDone could not safely record the stopping event; the incident timeline would be incomplete: " +
            errorText(error),
        },
        ctx,
      );
      return;
    }

    try {
      requestOneCorrection(await evaluateGate(ctx), ctx);
    } catch (error) {
      requestOneCorrection(
        {
          schema_version: 1,
          decision: "block",
          verdict: "INCONCLUSIVE",
          reason: "BeforeDone could not evaluate completion evidence: " + errorText(error),
        },
        ctx,
      );
    }
  });

  pi.on("session_shutdown", async (sourceEvent, ctx) => {
    await persistObserved(
      event(ctx, "SessionEnded", { attributes: { reason: sourceEvent.reason } }),
      ctx,
    );
  });
}
`
